### ISSUE TITLE
Nuget package updated

### ISSUE THREAD

**Issue by vertigra** [nahueltaibo/gamepad#7]
Will the nuget package be updated after replacing netcoreapp 2.1 => netstandard 2.1?

**Comment by nahueltaibo** [comment]
Im on it, first trying to create better pr and ci pipelines to ensure its good to publish a new version to nuget

**Comment by vertigra** [comment]
Thank you very much. I did a test build on rpi 4b. But I haven't checked on the physical controller yet. I'll do it later this week.

**Comment by nahueltaibo** [comment]
Hanks @vertigra ,

I also just pushed the latest version to nuget:
https://www.nuget.org/packages/Gamepad/1.1.0

Would you please help me validate that everything is working fine with it?

Thanks for your contribution! It means a lot to everyone using this package!

**Comment by vertigra** [comment]
Hi @nahueltaibo 

I checked the latest version on XBox Elite Controller v.2 by attaching it to Raspberry 4b via usb and everything works fine. I need a little more time to check more thoroughly on other joystick models.

Thanks for the great package!

**Comment by nahueltaibo** [comment]
Thanks @vertigra I'll close the issue then
